// <auto-generated />
using System;
using ActivityEvent.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Template.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200221204105_Seventh")]
    partial class Seventh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ActivityEvent.Models.Act", b =>
                {
                    b.Property<int>("ActId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Duration");

                    b.Property<DateTime>("Time");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Units")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("ActId");

                    b.HasIndex("UserId");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("ActivityEvent.Models.ActPart", b =>
                {
                    b.Property<int>("ActPartId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActId");

                    b.Property<int>("UserId");

                    b.HasKey("ActPartId");

                    b.HasIndex("ActId");

                    b.HasIndex("UserId");

                    b.ToTable("ActParts");
                });

            modelBuilder.Entity("ActivityEvent.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ActivityEvent.Models.Act", b =>
                {
                    b.HasOne("ActivityEvent.Models.User", "Coordinator")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ActivityEvent.Models.ActPart", b =>
                {
                    b.HasOne("ActivityEvent.Models.Act", "Act")
                        .WithMany("Participants")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ActivityEvent.Models.User", "Participant")
                        .WithMany("Acts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
